
title: My Resume
url: 'http://austinbrooks.pro'
baseurl: '/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Sections
#Decide which sections to include in your resume
resume_section_profile:       true
resume_section_experience:    true
resume_section_education:     true
resume_section_projects:      false
resume_section_skills:        true
resume_section_language:      false
resume_section_interests:     false
resume_section_about:         true

#Profile information
name: Austin Brooks
tagline: Industrial Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: c[dot]austin[dot]brooks[at]gatech[dot]edu
phone: N/A
website: austinbrooks.pro #do not add http://
linkedin: caustinbrooks
github: caustinbrooks
twitter: '@caustinbrooks'

#Update all the sections by editing the files inside _includes folder.
